version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: bambisleep-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: brandynette
      MONGO_INITDB_ROOT_PASSWORD: CNNvfZi
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - bambisleep-network
    restart: unless-stopped
    command: ["--bind_ip_all"]

networks:
  bambisleep-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  mongodb-data:
